# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TaketoGo < Formula
  desc "A tiny helper utility to make access to servers eaiser for different projects and environments."
  homepage "https://github.com/ivan-leschinsky/taketo-go"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.2.1/taketo-darwin-amd64", using: :nounzip
      sha256 "7faa6547bf0b47986b82607e8292f39d74c65a119e9c8fef0c37ab18177a94e3"

      define_method(:install) do
        bin.install "taketo-darwin-amd64" => "taketo-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.2.1/taketo-darwin-arm64", using: :nounzip
      sha256 "19d713edeb306152d72f0d4f290baf01ece87ef95019e63a3db8a73be3bcf2a7"

      define_method(:install) do
        bin.install "taketo-darwin-arm64" => "taketo-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.2.1/taketo-linux-amd64", using: :nounzip
      sha256 "3ff18b0fc66e165f1ea470652ea6551c93f294efc2fe621634454fcdec9106fa"
      define_method(:install) do
        bin.install "taketo-linux-amd64" => "taketo-go"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.2.1/taketo-linux-arm", using: :nounzip
      sha256 "256b1c34f088d5d2f2db7fef5d0eb4bf36121e3d87a72e1e1e0e794fa081a6a9"
      define_method(:install) do
        bin.install "taketo-linux-arm" => "taketo-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.2.1/taketo-linux-arm64", using: :nounzip
      sha256 "73635cbbb8bef1bbd727aeae5855526fe69556691ddd5281be906a79810fc3e0"
      define_method(:install) do
        bin.install "taketo-linux-arm64" => "taketo-go"
      end
    end
  end

  test do
    system "#{bin}/taketo-go --version"
  end
end
