# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TaketoGo < Formula
  desc "A tiny helper utility to make access to servers eaiser for different projects and environments."
  homepage "https://github.com/ivan-leschinsky/taketo-go"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.2.0/taketo-darwin-amd64", using: :nounzip
      sha256 "e3c1afa0b2cf2aeaeae593b7c5a0962f31a4ccd407905e905ee77935ad4327e3"

      define_method(:install) do
        bin.install "taketo-darwin-amd64" => "taketo-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.2.0/taketo-darwin-arm64", using: :nounzip
      sha256 "009b7d03377f716e56b7420ff9d7a4c9376bba841c47c5e6072b3f8080952d95"

      define_method(:install) do
        bin.install "taketo-darwin-arm64" => "taketo-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.2.0/taketo-linux-amd64", using: :nounzip
      sha256 "ba1a195de45410c648ee337923fd6fc2c23cd09f1abd7f3b879a03dcf2ab32bb"
      define_method(:install) do
        bin.install "taketo-linux-amd64" => "taketo-go"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.2.0/taketo-linux-arm", using: :nounzip
      sha256 "a1defabd9b0d05bcc95f835b18a4d05324880e346da4d56b058ddf109eca2d17"
      define_method(:install) do
        bin.install "taketo-linux-arm" => "taketo-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.2.0/taketo-linux-arm64", using: :nounzip
      sha256 "220345f406b095bf77d6babcb2bf0dc57fbd056ebd3bd3ea2d9e1273a9d95fd0"
      define_method(:install) do
        bin.install "taketo-linux-arm64" => "taketo-go"
      end
    end
  end

  test do
    system "#{bin}/taketo-go --version"
  end
end
